#!/usr/bin/env bash

set -e

PROJECT_ROOT=$(dirname $0)/..
STUTTER_TEST_DATA_DIR=${PROJECT_ROOT}/test-data/

echo "prepare test data"
mkdir -p ${STUTTER_TEST_DATA_DIR}


echo "prepare file with 5000 rows (20,000 chars)"
if [ ! -f test-data/big_file ]; then
    while true; do echo "foo"; done         \
        | head -n 5000                      \
        > ${STUTTER_TEST_DATA_DIR}/big_file
fi

STUTTER_EXE=${STUTTER_EXE:-"stack exec stutter -- +RTS -K1k -RTS"}

echo "test constant space one stdin"
echo "input: 1,000,000 rows, 4,000,000 chars"
echo '(1,000,000 x "foo\n")'
echo "output: 1,000,000 rows, 8,000,000 chars"
echo '(1,000,000 x "foo-bar\n")'
echo "heap size: 2M"
while true; do echo "foo"; done                         \
    | head -n 1000000                                   \
    | ${STUTTER_EXE} +RTS -M2M -RTS '(@-)-bar' \
    | wc -c

echo "test constant space file read"
echo "input: 5,000 rows, 20,000 chars"
echo '(5,000 x "foo\n")'
echo "output: 5,000 rows, 20,000 chars"
echo '(5,000 x "foo\n")'
echo "heap size: 2M"
${STUTTER_EXE} +RTS -M2M -RTS "(@${STUTTER_TEST_DATA_DIR}/big_file)" \
    | wc -c

echo "test constant space file product"
echo "input: 5,000 rows, 20,000 chars"
echo '(5,000 x "foo\n")'
echo "output: 25,000,000 rows, 175,000,000 chars"
echo '(5,000 x 5,000 x "foofoo\n")'
echo "heap size: 2M"
echo "Print every 1,000,000 elements to keep CI alive:"
${STUTTER_EXE} +RTS -M2M -RTS "(@${STUTTER_TEST_DATA_DIR}/big_file)(@${STUTTER_TEST_DATA_DIR}/big_file)" \
    | awk 'NR%1000000==0'
